const counterStyles = {
  mainContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
  },

  counterContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "0px",
  },

  heading: {
    fontFamily: "Roboto",
    fontSize: "20px",
    fontWeight: 600,
    color: "#000",
  },

  counterNum: {
    fontFamily: "Roboto",
    fontSize: "50px",
    fontWeight: 200,
    color: "green",
  },

  buttons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "20px",
  },

  increment: {
    border: "0px",
    outline: "none",
    width: "130px",
    height: "40px",
    borderRadius: "6px",
    color: "#fff",
    fontWeight: 600,
    fontFamily: "Roboto",
    fontSize: "15px",
    backgroundColor: "rgb(170, 20, 245)",
    cursor: "pointer",
    "&:hover": {
      border: "0px",
      outline: "none",
      width: "130px",
      height: "40px",
      borderRadius: "6px",
      color: "#fff",
      fontWeight: 600,
      fontFamily: "Roboto",
      fontSize: "15px",
      backgroundColor: "rgb(170, 20, 245)",
      cursor: "pointer",
    },
  },

  decrement: {
    border: "0px",
    outline: "none",
    width: "130px",
    height: "40px",
    borderRadius: "6px",
    color: "#fff",
    fontWeight: 600,
    fontFamily: "Roboto",
    fontSize: "15px",
    backgroundColor: "rgb(229, 113, 18)",
    cursor: "pointer",
    "&:hover": {
      border: "0px",
      outline: "none",
      width: "130px",
      height: "40px",
      borderRadius: "6px",
      color: "#fff",
      fontWeight: 600,
      fontFamily: "Roboto",
      fontSize: "15px",
      backgroundColor: "rgb(229, 113, 18)",
      cursor: "pointer",
    },
  },

  reset: {
    border: "0px",
    outline: "none",
    width: "130px",
    height: "40px",
    borderRadius: "6px",
    color: "#fff",
    fontWeight: 600,
    fontFamily: "Roboto",
    fontSize: "12px",
    backgroundColor: "#06e3c9",
    cursor: "pointer",
    "&:hover": {
      border: "0px",
      outline: "none",
      width: "130px",
      height: "40px",
      borderRadius: "6px",
      color: "#fff",
      fontWeight: 600,
      fontFamily: "Roboto",
      fontSize: "12px",
      backgroundColor: "#06e3c9",
      cursor: "pointer",
    },
  },

  resetDisable: {
    border: "0",
    outline: "none",
    width: "130px",
    height: "40px",
    borderRadius: "6px",
    color: "#fff",
    fontWeight: 600,
    fontFamily: "Roboto",
    fontSize: "12px",
    backgroundColor: "#666",
    cursor: "pointer",
    "&:hover": {
      border: "0",
      outline: "none",
      width: "130px",
      height: "40px",
      borderRadius: "6px",
      color: "#fff",
      fontWeight: 600,
      fontFamily: "Roboto",
      fontSize: "12px",
      backgroundColor: "#666",
      cursor: "pointer",
    },
  },
};

export default counterStyles;
